public/options.html, src/content.ts, src/lib/config-repository.ts, src/options.ts
#7
- feat: can insert account menu button background
- fix: invert button text correctly
=> feat: change account menu button color

.eslintrc.js, package.json, public/options.css, src/content.ts, src/lib/browser-storage.ts, src/lib/config-repository.ts, yarn.lock
#15
- feat: heighten option
- fix: eslint with prettier config
- fix: no airbnb lint
- fix: ignore eslintrc itself
- refactor: no bool eval without any assignment
=> feat: issues from interview phase1

public/manifest.json, src/content.ts
Catch up to update 2021-11-22
https://github.com/xhiroga/aws-peacock-management-console/issues/27
=> feat: aws-update-2021-11-22

README.md
explanation abount account name
=> docs: explanation abount account name

README.md, package.json, public/manifest.json, src/content.ts, src/options.ts, src/scraping.ts, yarn.lock
For firefox extension
https://github.com/xhiroga/aws-peacock-management-console/issues/26
=> feat: firefox

src/content.ts
https://github.com/xhiroga/aws-peacock-management-console/issues/32
=> fix: avoid to use aria-label

src/content.ts
Co-authored-by: Kaito Udagawa <umireon@gmail.com>
https://github.com/xhiroga/aws-peacock-management-console/issues/36
=> feat: re-use account menu button inner text when aws sso

src/content.ts
https://github.com/xhiroga/aws-peacock-management-console/issues/35
=> feat: change aws service namae colors

package.json, src/content.ts, yarn.lock
#23
とりあえず自動判別されて動きます
Configのフォーマットが変わったら動かなくなる可能性はありますが、それでも最初の数文字を見ればYAMLかJSONCかは区別できるはずです
=> Support YAML config

src/content.ts
- use Try-Catch instead of regex
- make sure account id is string
https://github.com/xhiroga/aws-peacock-management-console/issues/23
=> feat: improve YAML support

README.md
Firefox add-on link
https://github.com/xhiroga/aws-peacock-management-console/issues/48
=> docs: firefox add-on link

.github/ISSUE_TEMPLATE/feature-request.yml
I want to know the motivation of feature request
=> chore: feature request needs motivation

examples/shared.jsonc
Host sample jsonc
https://github.com/xhiroga/aws-peacock-management-console/issues/44
=> chore: host sample jsonc

public/options.css, public/options.html, src/options.ts
=> feat: re-design option screen

src/content.ts
- chore: fix footer selector
- fix: icons
https://github.com/xhiroga/aws-peacock-management-console/issues/62
=> fix: invert icons

src/content.ts
- Enable to invert quick setting button
- Refactoring
https://github.com/xhiroga/aws-peacock-management-console/issues/72
=> feat: quick setting button

package.json, public/manifest.json
https://github.com/xhiroga/aws-peacock-management-console/pull/77
=> chore: 2.10

jest.config.js, package.json, public/manifest.json, src/awsapps.ts, src/content.ts, src/lib/account-name-repository.ts, src/lib/scraping.test.ts, src/lib/scraping.ts, src/scraping.ts, webpack.config.ts, yarn.lock
Update logic, refactor and finally add unit test.
#79
=> fix: update for AWS access portal 2024-06

package.json, public/manifest.json
=> chore: update to 2.11

src/awsapps.ts, src/content.ts, src/lib/account-name-repository.ts, src/lib/util.test.ts, src/lib/util.ts
`mergeAccounts()` saved duplicated accounts. Fix it and add unit tests.
=> fix: reset accounts and save duplicate accounts (and refactor)

package.json, public/manifest.json
=> chore: 2.12

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/feature-request.yml
=> chore: sign-in method in issue template

package.json, public/manifest.json
=> chore: 2.13

src/content.ts
Multi Session UI support (Account menu background color)
https://github.com/xhiroga/aws-peacock-management-console/issues/95#issuecomment-2600586309
=> feat: handle background color correctly, if multi session enabled

src/content.ts
Append tags for inserted style tags
=> chore: Debug CSS easier

.github/PULL_REQUEST_TEMPLATE.md, .vscode/settings.json, public/options.css, public/options.html, src/content.ts, src/lib/config-repository.ts, src/lib/util.ts, src/options.ts
Enable settings to be applied using regular expression patterns for usernames.
https://github.com/xhiroga/aws-peacock-management-console/pull/90
https://github.com/xhiroga/aws-peacock-management-console/issues/111
https://github.com/xhiroga/aws-peacock-management-console/pull/112
=> feat: Enable settings to be applied using regular expression patterns for usernames.

src/lib/util.test.ts, src/lib/util.ts
=> Fix/tamagokakedon fix/display account name 20250625
